language: java
jdk:
  - oraclejdk8
  - oraclejdk7

before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/target/classes/resource/
  - echo "$JIDE_COMPANY_NAME" > $TRAVIS_BUILD_DIR/target/classes/resource/jidelicense.txt
  - echo "$JIDE_PROJECT_NAME" >> $TRAVIS_BUILD_DIR/target/classes/resource/jidelicense.txt
  - echo "$JIDE_LICENSE_KEY" >> $TRAVIS_BUILD_DIR/target/classes/resource/jidelicense.txt
  - if [ -n "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG" >> $TRAVIS_BUILD_DIR/target/classes/resource/version.txt; fi

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  region: $S3_REGION
  upload-dir: build/$TRAVIS_BRANCH
  local-dir: $TRAVIS_BUILD_DIR/target/build
  skip_cleanup: true
  acl: public_read
  on:
      all_branches: true
      jdk: oraclejdk7
