language: java
jdk:
  - oraclejdk8
  - oraclejdk7

# Allow to run tests that depend on UI
env:
  - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start

before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/target/classes/resource/
  - echo "$JIDE_COMPANY_NAME" >> $TRAVIS_BUILD_DIR/target/classes/resource/jidelicense.txt
  - echo "$JIDE_PROJECT_NAME" >> $TRAVIS_BUILD_DIR/target/classes/resource/jidelicense.txt
  - echo "$JIDE_LICENSE_KEY" >> $TRAVIS_BUILD_DIR/target/classes/resource/jidelicense.txt
  - if [ -n "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG" >> $TRAVIS_BUILD_DIR/target/classes/resource/version.txt; fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then echo "$TRAVIS_BRANCH" >> $TRAVIS_BUILD_DIR/target/classes/resource/branch.txt; fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then echo "$TRAVIS_BUILD_NUMBER" >> $TRAVIS_BUILD_DIR/target/classes/resource/build.txt; fi
  - echo $(date +"%Y-%m-%d") >> $TRAVIS_BUILD_DIR/target/classes/resource/date.txt

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  region: $S3_REGION
  upload-dir: build/$TRAVIS_BRANCH
  local-dir: $TRAVIS_BUILD_DIR/target/build
  skip_cleanup: true
  acl: public_read
  on:
      all_branches: true
      jdk: oraclejdk7

deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: mA6DaAr2VXyE8Zn0LPq7XX3e3/Dnlk3trkNDhuWNbs4jCISbCLBJalJEaovgd392/tKYjmOdN7kN+PUVyOwQZgwl2v7Q4cx0epMksibLhjICvVegGRMM/epPaOBqrQXy31gZN6RDKxVG/XFw9K9ez3TUZr0GmsjaRjQ9rNL62eRwvywrNzNFHLDJAWtM4Jl/DijN1LHO17OcecQArRA/Dk8y2r52DlKBXqQlksqfr3slJOH2natY/Nf2ZkfEyYZNRZ+6J9uKbkCTFncVoN80V/1nlA9QQ17gJx5ZnhpWqytebMgdRBKHgVECuLRHfw7vUzkQkk3V9U/VMxYTassWYYcfV9PNWCSshL4czl5LjMzRU65M+H2l/pISFwpwFM4E5u7A8lJ4KWclgfU7vFn/iWkb95NeAbYvPOfvB4OGIiaSI8xTWWL/tKdX+hmjWIKPSdhQd8B26syfJeqL2DcgE8uFjgisLZuBlWl7dKr11ausTPcA8lu4A4dWsZpuBVIPT6/Oi0XEFYVaTiy3CSV/XVV1XORME6G3UC0098DlWW/sZw5dA6jv/cf0o4IwttYDZdNq8fQVL2aXM7uJpv54gAjtBUpoFb/nNnkMw6MuN/xSzcgKs/ZWQk3HSPNuSuiWi/XPftNPUYJIJsZCeZscfKIBupzUhU9W8NX4r+LmYHA=
  file: $TRAVIS_BUILD_DIR/target/build/voxelshop-bin.zip
  on:
    repo: simlu/voxelshop
    branch: qa
    tags: true

deploy:
  provider: releases
  api_key:
    secure: mA6DaAr2VXyE8Zn0LPq7XX3e3/Dnlk3trkNDhuWNbs4jCISbCLBJalJEaovgd392/tKYjmOdN7kN+PUVyOwQZgwl2v7Q4cx0epMksibLhjICvVegGRMM/epPaOBqrQXy31gZN6RDKxVG/XFw9K9ez3TUZr0GmsjaRjQ9rNL62eRwvywrNzNFHLDJAWtM4Jl/DijN1LHO17OcecQArRA/Dk8y2r52DlKBXqQlksqfr3slJOH2natY/Nf2ZkfEyYZNRZ+6J9uKbkCTFncVoN80V/1nlA9QQ17gJx5ZnhpWqytebMgdRBKHgVECuLRHfw7vUzkQkk3V9U/VMxYTassWYYcfV9PNWCSshL4czl5LjMzRU65M+H2l/pISFwpwFM4E5u7A8lJ4KWclgfU7vFn/iWkb95NeAbYvPOfvB4OGIiaSI8xTWWL/tKdX+hmjWIKPSdhQd8B26syfJeqL2DcgE8uFjgisLZuBlWl7dKr11ausTPcA8lu4A4dWsZpuBVIPT6/Oi0XEFYVaTiy3CSV/XVV1XORME6G3UC0098DlWW/sZw5dA6jv/cf0o4IwttYDZdNq8fQVL2aXM7uJpv54gAjtBUpoFb/nNnkMw6MuN/xSzcgKs/ZWQk3HSPNuSuiWi/XPftNPUYJIJsZCeZscfKIBupzUhU9W8NX4r+LmYHA=
  file: $TRAVIS_BUILD_DIR/target/build/voxelshop-bin.zip
  on:
    repo: simlu/voxelshop
    branch: master
    tags: true